import 'package:json_annotation/json_annotation.dart';

part 'course_model.g.dart'; // This file will be generated by json_serializable

@JsonSerializable()
class Course {
  String id;
  String name;
  String org;
  String desc;
  String coursePhoto;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  String createdBy;
  String status;

  Course({
    required this.coursePhoto,
    this.createdAt,
    this.updatedAt,
    required this.id,
    required this.name,
    required this.org,
    required this.desc,
    required this.createdBy,
    required this.status,
  });

  // Add factory methods to enable deserialization from JSON
  factory Course.fromJson(Map<String, dynamic> json) => _$CourseFromJson(json);

  // Add a toJson method to enable serialization to JSON
  Map<String, dynamic> toJson() => _$CourseToJson(this);
}
